on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Pack vsix
      run: npx vsce package

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: devicetree
        path: devicetree-*.vsix
